title: React Curriculum - 24W
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://lawtlee.github.io/React-Curriculum/

aux_links:
  Template Repository: https://github.com/lawtlee/React-Curriculum-Docs
